# Generated by Django 2.0.1 on 2019-03-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crossservice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.TextField(default='Denis', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.TextField(default='Innopolis', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='second_nmae',
            field=models.TextField(default='Denis', max_length=50),
            preserve_default=False,
        ),
    ]
